export const PROCESSES_ISFETCHING = 'PROCESSES_ISFETCHING'
export const PROCESSES_SAVE = 'PROCESSES_SAVE'

export const JOBS_ISFETCHING = 'JOBS_ISFETCHING'
export const JOBS_SAVE = 'JOBS_SAVE'
export const JOBS_SET_PROCESS_ID = 'JOBS_SET_PROCESS_ID'